# Generated by Django 2.2.1 on 2019-05-31 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenStreetMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('osm_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('housenumber', models.CharField(blank=True, max_length=100)),
                ('amenity', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('postcode', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=250)),
                ('street', models.CharField(blank=True, max_length=250)),
                ('website', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('religion', models.CharField(blank=True, max_length=250)),
                ('opening_hours', models.CharField(blank=True, max_length=250)),
                ('internet_access', models.CharField(blank=True, max_length=250)),
                ('building', models.CharField(blank=True, max_length=250)),
                ('denomination', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'OpenStreetMap',
                'verbose_name_plural': 'OpenStreetMaps',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('school_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude27', models.CharField(blank=True, max_length=100)),
                ('longitude27', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('region', models.CharField(blank=True, max_length=250)),
                ('gender', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('directorate', models.CharField(blank=True, max_length=250)),
                ('code', models.CharField(blank=True, max_length=250)),
                ('osm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='pubsub.OpenStreetMap')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='GeoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('geoname_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('alt_name', models.CharField(blank=True, max_length=250)),
                ('country_code', models.CharField(blank=True, max_length=250)),
                ('location_map', models.CharField(blank=True, max_length=250)),
                ('feature_class', models.CharField(blank=True, max_length=250)),
                ('feature_code', models.CharField(blank=True, max_length=250)),
                ('parent_feature', models.CharField(blank=True, max_length=250)),
                ('parent_country', models.CharField(blank=True, max_length=250)),
                ('nearby_features', models.CharField(blank=True, max_length=250)),
                ('wikipedia_article', models.CharField(blank=True, max_length=250)),
                ('osm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geonames', to='pubsub.OpenStreetMap')),
            ],
            options={
                'verbose_name': 'GeoNames',
                'verbose_name_plural': 'GeoNames',
            },
        ),
    ]
