# Generated by Django 2.2.1 on 2019-06-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubsub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('wiki_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('page_id', models.CharField(blank=True, max_length=250)),
                ('last_rev_id', models.CharField(blank=True, max_length=250)),
                ('ns', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(blank=True, max_length=250)),
                ('modified', models.CharField(blank=True, max_length=250)),
                ('osm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_entities', to='pubsub.OpenStreetMap')),
            ],
            options={
                'verbose_name': 'WikiEntity',
                'verbose_name_plural': 'WikiEntities',
            },
        ),
    ]
